#!/bin/sh

if [ "yes" == "${RUN_IN_DOCKER}" ]; then
	echo "remove cache files."
	\rm -vf  /data/config/conf.d/generated.conf
	\rm -rvf /data/config/generated.d/*
	
	update-resolve
else
	echo "remove cache only run in docker." >&2
fi

echo "try start nginx server."

exec nginx -g "daemon off;"
